# Generated by Django 5.2.6 on 2025-11-11 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phonenumber',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinValueValidator(80000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
