# Generated by Django 5.2.6 on 2025-12-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_imagegallery'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagegallery',
            table=None,
        ),
    ]
