# Generated by Django 5.2.6 on 2025-12-08 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_alter_imagegallery_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='ip',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
