# Generated by Django 5.2.6 on 2025-12-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_remove_orderproduct_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='status',
        ),
    ]
